name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag verifiedemployeeissuance:$(date +%s)
    - name: Build and publish Docker Images to GitHub Container registry
    # You may pin to the exact commit or the version.
    # uses: VaultVulp/gp-docker-action@3c0a6ca5c66e31614579048b57259114fb69ac28
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Docker Image name
        image-name: verifiedemployeeissuance
        # Docker Image tag
        image-tag: $(date +%s) # optional, default is latest
        # Extract git-tag from repository
        # extract-git-tag: # optional, default is false
        # Dockerfile name
        # dockerfile: # optional, default is Dockerfile
        # Path to build context
        # build-context: # optional, default is .
        # Pull the image before buiding it
        # pull-image: true # optional, default is false
        # Multiple tags that will be attached to a built image
        additional-image-tags: latest # optional, default is 
        # Target image platform/platforms
        image-platform: amd64 # optional, default is 
        # Any additional docker build arguments as a string
        # custom-args: # optional, default is 
              
