name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag verifiedemployeeissuance:$(date +%s)

    - name: "Github Container Registry: Build and push Docker image"
      # You may pin to the exact commit or the version.
      # uses: pmorelli92/github-container-registry-build-push@fc48636de278363701ac07b6317820e4dfb514d6
      uses: pmorelli92/github-container-registry-build-push@2.1.0
      with:
        # Token such as GITHUB_TOKEN that has `write:packages` scope to authenticate against GCHR.
        github-push-secret: ${{ secrets.GITHUB_TOKEN }}
        # Docker Image name
        docker-image-name: verifiedemployeeissuance
        # Docker Image tag
        docker-image-tag: latest # optional, default is latest
        # Dockerfile path and name
        # dockerfile-path: # optional, default is Dockerfile
        # Path to the build context
        # build-context: # optional, default is .
        # If 'true', skip pushing the image
        # build-only: # optional, default is false
          
